blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('search/<str:q>/', views.PostSearch.as_view()),
    path('delete_comment/<int:pk>/',views.delete_comment),
    path('update_comment/<int:pk>/',views.CommentUpdate.as_view()),
    path('update_post/<int:pk>/',views.PostUpdate.as_view()),
    path('create_post/',views.PostCreate.as_view()),
    path('tag/<str:slug>/', views.tag_page),
    path('category/<str:slug>/', views.category_page),
    path('<int:pk>/new_comment/',views.new_comment),
    path('<int:pk>/',views.PostDetail.as_view()),
    path('',views.PostList.as_view()),
]

dj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('program/', include('program.urls')),
    path('markdownx/',include('markdownx.urls')),
    path('accounts/',include('allauth.urls')),
    path('', include('single_pages.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from markdownx.models import MarkdownxField
from markdownx.utils import markdown
import os

class Tag(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/blog/tag/{self.slug}/'    


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/blog/category/{self.slug}/'    

    class Meta:
        verbose_name_plural = 'Categories'

class Post(models.Model):
    title = models.CharField(max_length=30)
    hook_text = models.CharField(max_length=100, blank=True)
    content = MarkdownxField()
    head_image = models.ImageField(upload_to='blog/images/%Y/%m/%d/',blank=True)
    file_upload = models.FileField(upload_to='blog/files/%Y/%m/%d/',blank=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)
    tags = models.ManyToManyField(Tag,blank=True)

    def __str__(self):
        return f'[{self.pk}]{self.title} :: {self.author}'
    
    def get_absolute_url(self):
        return f'/blog/{self.pk}/'
    
    def get_file_name(self):
        return os.path.basename(self.file_upload.name)
    
    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]

    def get_content_markdown(self):
        return markdown(self.content)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.author}::{self.content}'

    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}'

blog/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("content",)

blog/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import get_object_or_404
from .models import Post, Category, Tag, Comment
from .forms import CommentForm
from django.core.exceptions import PermissionDenied
from django.utils.text import slugify
from django.db.models import Q


class PostList(ListView):
    model = Post
    ordering = '-pk'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(PostList, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count()
        return context   


def category_page(request, slug):
    if slug == 'no_category':
        category = '미분류'
        post_list = Post.objects.filter(category=None)
    else:
        category = Category.objects.get(slug=slug)
        post_list = Post.objects.filter(category=category)

    return render(
        request,
        'blog/post_list.html',
        {
            'post_list': post_list,
            'categories': Category.objects.all(),
            'no_category_post_count': Post.objects.filter(category=None).count(),
            'category': category,
        }
    )

def tag_page(request, slug):
    tag = Tag.objects.get(slug=slug)
    post_list = tag.post_set.all()

    return render(
    request,
    'blog/post_list.html',
    {
        'post_list': post_list,
        'tag': tag,
        'categories': Category.objects.all(),
        'no_category_post_count': Post.objects.filter(category=None).count(),
    }
)

def new_comment(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk)

        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
        else:
            return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied


class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post = comment.post
    if request.user.is_authenticated and request.user == comment.author:
        comment.delete()
        return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied 

class PostDetail(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count()
        context['comment_form'] = CommentForm
        return context      

class PostCreate(LoginRequiredMixin,UserPassesTestMixin,CreateView):
    model = Post
    fields = ['title','hook_text','content','head_image','file_upload','category']

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def form_valid(self,form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_staff or current_user.is_superuser):
            form.instance.author = current_user
            response = super(PostCreate,self).form_valid(form)

            tags_str = self.request.POST.get('tags_str')
            if tags_str:
                tags_str = tags_str.strip()

                tags_str = tags_str.replace(',',';')
                tags_list = tags_str.split(';')

                for t in tags_list:
                    t = t.strip()
                    tag, is_tag_created = Tag.objects.get_or_create(name=t)
                    if is_tag_created:
                        tag.slug = slugify(t,allow_unicode=True)
                        tag.save()
                    self.object.tags.add(tag)

            return response

        else:
            return redirect('/blog/')

class PostUpdate(LoginRequiredMixin,UpdateView):
    model = Post
    fields = ['title','hook_text','content','head_image','file_upload','category','tags']

    template_name: 'blog/post_update_form.html'

    def get_context_data(self, **kwargs):
        context = super(PostUpdate, self).get_context_data()
        if self.object.tags.exists():
            tags_str_list = list()
            for t in self.object.tags.all():
                tags_str_list.append(t.name)
            context['tags_str_default'] = ';'.join(tags_str_list)
        return context 

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate,self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied
        

    def form_valid(self,form):
            response = super(PostUpdate,self).form_valid(form)
            self.object.tags.clear()

            tags_str = self.request.POST.get('tags_str')
            if tags_str:
                tags_str = tags_str.strip()
                tags_str = tags_str.replace(',',';')
                tags_list = tags_str.split(';')

                for t in tags_list:
                    t = t.strip()
                    tag, is_tag_created = Tag.objects.get_or_create(name=t)
                    if is_tag_created:
                        tag.slug = slugify(t,allow_unicode=True)
                        tag.save()
                    self.object.tags.add(tag)

            return response


class PostSearch(PostList):
    paginate_by = None

    def get_queryset(self):
        q = self.kwargs['q']
        post_list = Post.objects.filter(
            Q(title__contains=q) | Q(tags__name__contains=q)
        ).distinct()
        return post_list

    def get_context_data(self, **kwargs):
        context = super(PostSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search: {q} ({self.get_queryset().count()})'

        return context

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block head_title %}Blog{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/46660e958a.js" crossorigin="anonymous"></script>
    <link href="blog-post.css" rel="stylesheet">
</head>

<body>
    {% include 'blog/navbar.html' %}
    <div class="container my-3">
        <div class="row">
            <div class="col-md-8 col-lg-9" id="main-area">
                {% block main_area %}
                {% endblock %}
            </div>
    
            <div class="col-md-4 col-lg-3">
                <!-- Search Widget -->
                <div class="card my-4">
                    <h5 class="card-header">Search</h5>
                    <div class="card-body">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search for..." id="search-input">
                            <span class="input-group-btn">
                                    <button class="btn btn-secondary" type="button" onclick="searchPost();">Go!</button>
                                </span>
                        </div>
                    </div>
                </div>
    
                <!-- Categories Widget -->
                <div class="card my-4" id="categories-card">
                    <h5 class="card-header">Categories</h5>
                    <div class="card-body">
                        <div class="row">
                            <ul> 
                                {% for category in categories %}
                                <li>
                                    <a href="{{ category.get_absolute_url }}">{{ category }} ({{ category.post_set.count }})</a>
                                </li>
                                {% endfor %}
                                <li>
                                    <a href="/blog/category/no_category/">미분류 ({{ no_category_post_count }})</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        function searchPost(){
            let searchValue = document.getElementById('search-input').value.trim();
            if (searchValue.length > 1){
                location.href="/blog/search/" + searchValue + "/";
            }
            else{
                alert('검색어('+ searchValue +')가 너무 짧습니다.');
            }
        };
    
        document.getElementById('search-input').addEventListener('keyup', function(event){
            if(event.key === 'Enter'){
                searchPost();
            }
        });
    </script>

    {% include 'blog/footer.html' %} 
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"  crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/base_full_width.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">

<head>
    <title>{% block head_title %}Blog{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/46660e958a.js" crossorigin="anonymous"></script>
</head>

<body>
    {% include 'blog/navbar.html' %}
    
    <div class="container my-3">
        <div class="row">
            <div class="col-12" id="main-area">
            {% block main_area %} 
            {% endblock %}
            </div>
        </div>
    </div>

    {% include 'blog/footer.html' %} 
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"  crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/comment_form.html
{% extends 'blog/base_full_width.html'%} 
{% load crispy_forms_tags %}

{% block head_title %}Edit Comment - Blog {% endblock %}

{% block main_area %}
    <h1>Edit Comment</h1>
    <hr/>
    <form method="post" id="comment-form">{% csrf_token %}
            {{ form | crispy }}
            <br/>
            <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>
{% endblock %}

blog/templates/blog/footer.html
<!-- Footer-->
<footer class="py-3 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">
      Copyright &copy; JH's A to Z 2022
    </p>
  </div>

blog/templates/blog/navbar.html
{% load socialaccount %}

<!-- Responsive navbar-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="/">CAKD7</a>
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/blog/">Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/about_me/">About Me</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/program/">Program</a>
        </li>
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdownMenuLink"
            role="button"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
          >
          📌
        </a>
        <div
          class="dropdown-menu"
          aria-labelledby="navbarDropdownMenuLink"
        >
          <a class="dropdown-item" href="https://impartial-tenor-0ea.notion.site/f29f89c0d1f045a693c582cc0d4b68de">Notion</a>
          <a class="dropdown-item" href="https://github.com/veryberry030">Github</a>
          {% if user.is_authenticated %}  
            <a class="dropdown-item" href="/accounts/logout/">Log Out</a>
          {% else %}
          </div>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a
            class="nav-link"
            href="#"
            data-toggle="modal"
            data-target="#loginModal"
            >Log In</a
          >
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
<!-- Modal -->
<div
  class="modal fade"
  id="loginModal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="logInModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="loginModalLabel">
          <i class="fas fa-sign-in-alt"></i>&nbsp Log In
        </h5>
        <button
          type="button"
          class="close"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-6">
            <a role="button" 
              class="btn btn-outline-dark btn-block btn-sm"
              href="{% provider_login_url 'google' %}">
              <i class="fab fa-google"></i>&nbsp&nbsp Log in with Google
            </a>
            <a role="button" 
              class="btn btn-outline-dark btn-block btn-sm"
              href="/accounts/login/"
            >
              <i class="far fa-envelope"></i>&nbsp&nbsp Log in with Username
            </a>
          </div>
          <div class="col-md-6">
            <a role="button" 
              class="btn btn-outline-dark btn-block btn-sm"
              href="/accounts/signup/"
            >
              <i class="far fa-envelope"></i>&nbsp&nbsp Sign Up with E-mail
            </a>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button
          type="button"
          class="btn btn-secondary"
          data-dismiss="modal"
        >
          Close
        </button>
      </div>
    </div>
  </div>
</div>       

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    {{ post.title }} - Blog
{% endblock %}


{% block main_area %}
    <div id="post-area">

        {% if post.category %}
            <span class="badge badge-secondary float-right">{{ post.category }}</span>
        {% else %}
            <span class="badge badge-secondary float-right">미분류</span>
        {% endif %}
        <!-- Title -->
        <h1 class="mt-4">{{ post.title }}</h1>
        <h5 class="text-muted">{{ post.hook_text }}</h5>
        <!-- Author -->
        <p class="lead">
            by
            <a href="#">{{ post.author | upper }}</a>
        </p>

        <hr>

        {% if user.is_authenticated and user == post.author %}
            <a class="btn btn-info btn-sm float-right" href="/blog/update_post/{{ post.pk }}/" role="button"><i class="fas fa-pen"></i>  Edit Post</a>
        {% endif %}

        <!-- Date/Time -->
        <p>Posted on {{ post.created_at }}</p>

        <hr>

        <!-- Preview Image -->
        {% if post.head_image %}
            <img class="img-fluid rounded" src="{{ post.head_image.url }}" alt="{{ post.title }} head_image">
        {% else %}
            <img class="img-fluid rounded" src="https://picsum.photos/seed/{{ post.id }}/800/200" alt="random_image">
        {% endif %}


        <hr>

        <!-- Post Content -->
        <p>{{ post.get_content_markdown | safe }}</p>

        {% if post.tags.exists %}
            <i class="fas fa-tags"></i>
            {% for tag in post.tags.all %}
                <a href="{{ tag.get_absolute_url }}" class="badge badge-light">{{ tag }}</a>
            {% endfor %}
            <br/>
            <br/>
        {% endif %}

        {% if post.file_upload %}
            <a href="{{ post.file_upload.url }}" class="btn btn-outline-dark" role="button" download>
                Download:

                {% if post.get_file_ext == 'csv' %}
                    <i class="fas fa-file-csv"></i>
                {% elif post.get_file_ext == 'xlsx' or post.get_file_ext == 'xls' %}
                    <i class="fas fa-file-excel"></i>
                {% elif post.get_file_ext == 'docx' or post.get_file_ext == 'doc' %}
                    <i class="fas fa-file-word"></i>
                {% else %}
                    <i class="far fa-file"></i>
                {% endif %}

                {{ post.get_file_name }}
            </a>
        {% endif %}

        <hr>
    </div>

    <div id="comment-area">
        <!-- Comments Form -->
        <div class="card my-4">
            <h5 class="card-header">Leave a Comment:</h5>
            <div class="card-body">
                {% if user.is_authenticated %}
                <form id="comment-form" method="POST" action="{{ post.get_absolute_url }}new_comment/">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ comment_form | crispy }}
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
                {% else %}
                    <a role="button" class="btn btn-outline-dark btn-block btn-sm" href="#" data-toggle="modal" data-target="#loginModal">Log in and leave a comment</a>
                {% endif %}
            </div>
        </div>

        {% if post.comment_set.exists %}
            {% for comment in post.comment_set.iterator %}
                <!-- Single Comment -->
                <div class="media mb-4" id="comment-{{ comment.pk }}">
                    <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                    <div class="media-body">
                        {% if user.is_authenticated and comment.author == user %}
                            <div class="float-right">
                                <a role="button"
                                   class="btn btn-sm btn-info"
                                   id="comment-{{ comment.pk }}-update-btn"
                                   href="/blog/update_comment/{{ comment.pk }}/">
                                    edit
                                </a>
                                <a role="button"
                                   href="#"
                                   id="comment-{{ comment.pk }}-delete-modal-btn"
                                   class="btn btn-sm btn-danger"
                                   data-toggle="modal" data-target="#deleteCommentModal-{{ comment.pk }}">
                                    delete
                                </a>
                            </div>

                            <!-- Modal -->
                            <div class="modal fade" id="deleteCommentModal-{{ comment.pk }}" tabindex="-1" role="dialog" aria-labelledby="deleteCommentModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="deleteModalLabel">Are You Sure?</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <del>{{ comment | linebreaks }}</del>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                            <a role="button" class="btn btn-danger" href="/blog/delete_comment/{{ comment.pk }}/">Delete</a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        {% endif %}
                        <h5 class="mt-0">
                            {{ comment.author.username }}
                            &nbsp;&nbsp;<small class="text-muted">{{ comment.created_at }}</small>
                        </h5>
                        <p>{{ comment.content | linebreaks }}</p>
                        {% if comment.created_at != comment.modified_at %}
                            <p class="text-muted float-right"><small>Updated: {{ comment.modified_at }}</small></p>
                        {% endif %}

                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base_full_width.html'%} 
{% load crispy_forms_tags %}

{% block head_title %}Create Post - Blog {% endblock %}

{% block main_area %}
    <h1>Create New Post</h1>
    <hr/>
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
            {{ form | crispy }}
            <div id = "div_id_tags_str">
                <label for="id_tags_str">Tags:</label>
                <input type="text" name="tags_str" id="id_tags_str" class="textinput textInput form-control">
            </div>
            <br/>
        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>
    {{ form.media }}
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block main_area %}

    {% if user.is_authenticated%}
        {% if user.is_superuser or user.is_staff %}
            <a class="btn btn-info btn-sm float-right" href="/blog/create_post/" role="button"><i class="fas fa-pen"></i>&nbsp;&nbsp;New Post</a>
        {% endif %}
    {% endif %}

    <h1>Blog
        {% if search_info %}<small class="text-muted">{{ search_info }}</small>{% endif %}
        {% if category %}<span class="badge badge-secondary">{{ category }}</span>{% endif %}
        {% if tag %}<span class="badge badge-light"><i class="fas fa-tags"></i>{{ tag }} ({{ tag.post_set.count }})</span>{% endif %}
    </h1>
    {% if post_list.exists %}

    {% for p in post_list %}
    <!-- Blog Post -->
    <div class="card mb-4" id="post-{{p.pk}}">
        {% if p.head_image %}
            <img class="card-img-top" src="{{ p.head_image.url }}" alt="{{ p }} head image">
        {% else %}
            <img class="card-img-top" src="https://picsum.photos/seed/{{ p.id }}/800/200" alt="random_image">
        {% endif %}
        <div class="card-body">
            {% if p.category %}
                <span class="badge badge-secondary float-right">{{ p.category }}</span>
            {% else %}
                <span class="badge badge-secondary float-right">미분류</span>
            {% endif %}

            <h2 class="card-title">{{ p.title}}</h2>
            {% if p.hook_text %}
                <h5 class="text-muted">{{ p.hook_text }}</h5>
            {% endif %}
            <!-- 마크다운 적용 -->
            <p class="card-text">{{ p.get_content_markdown | truncatewords_html:45 | safe }}</p>

            {% if p.tags.exists %}
                        <i class="fas fa-tags"></i>
                        {% for tag in p.tags.iterator %}
                            <a href="{{ tag.get_absolute_url }}"><span class="badge badge-pill badge-light">{{ tag }}</span></a>
                        {% endfor %}
                        <br/>
                        <br/>
                    {% endif %}

            <a href="{{ p.get_absolute_url }}" class="btn btn-primary">Read More &rarr;</a>
        </div>
        <div class="card-footer text-muted">
            Posted on {{ p.created_at}} by
            <a href="#">{{p.author | upper}}</a>
        </div>
    </div>
{% endfor %}

    {% else %}
        <h3>아직 게시물이 없습니다.</h3>
    {% endif %}

    {% if is_paginated %}

     <!-- Pagination -->
     <ul class="pagination justify-content-center mb-4">
        {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">&larr; Older</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">&larr; Older</a>
                </li>
            {% endif %}

            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Newer &rarr;</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">Newer &rarr;</a>
                </li>
            {% endif %}
    </ul>
    {% endif %}
{% endblock %}

blog/templates/blog/post_update_form.html
{% extends 'blog/base_full_width.html'%} 
{% load crispy_forms_tags %}


{% block head_title %}Edit Post - Blog {% endblock %}

{% block main_area %}
    <h1>Edit Post</h1>
    <hr/>
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
            {{ form | crispy }}
            <div id = "div_id_tags_str">
                <label for="id_tags_str">Tags:</label>
                <input type="text" name="tags_str" id="id_tags_str" class="textinput textInput form-control" value="{{ tags_str_default }}">
            </div>
            <br/>
        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>
    {{ form.media }}    
{% endblock %}